spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/calificaciones
    username: postgres
    password: admin1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  main:
    allow-circular-references: true

server:
  port: 8081

security:
  jwt:
    token:
      secret-key: "tu_clave_secreta_muy_larga_y_segura_para_firmar_tokens_jwt_2024"
      expire-length: 3600000  # 1 hora en milisegundos

logging:
  level:
    root: INFO
    com.uniandes: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG